---
apiVersion: v1
kind: Pod
metadata:
  name: factorio
spec:
  containers:
  - image: factoriotools/factorio:1.0.0
    name: factorio
    ports:
    - containerPort: 27015
      protocol: TCP
    - containerPort: 34197
      protocol: UDP

